# -*- coding: utf-8 -*-
"""551appAlertScraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-yQKIuOMphhc_OzctzbvGpMunHCkrSh
"""

import requests
from bs4 import BeautifulSoup
import re
import numpy as np
import pandas as pd

"""# Get our 21 alerts page links"""

pages=[]
crimeLinks = []
def get_pages(numPages):
  for i in range(numPages):
    pages.append('https://dps.usc.edu/category/alerts/page/'+str(i+1))

get_pages(20)

"""# Get each individual page containing incident level data within the 21 alerts pages"""

def get_alerts():
  for page in range(len(pages)):
    content = requests.get(pages[page])
    soup = BeautifulSoup(content.content, 'html.parser')
    Hs = soup.findAll('h1')
    links=[]
    for line in Hs:
      if "entry-title" in str(line):
        links.append(line.findAll('a', attrs={'href': re.compile("^https://")}))

# 10 crimes per page
    for index in range(10):
      crimeLinks.append(links[index][0].get('href'))

get_alerts

"""# Create individual lists for the crime, time, and location within each individual case. Similar indexes correspond to the same crime."""

crimes = []
times = []
locations=[]
for link in range(len(crimeLinks)):
  content = requests.get(crimeLinks[link])
  soup = BeautifulSoup(content.content, 'html.parser')
  crimes.append(soup.find('title').getText().split('|')[0].rstrip())
  Ps = soup.findAll('p')
  for tag in Ps:
    if 'DATE' in str(tag.contents[0]):
      try:
        times[link] = crimes[link] + str(tag.contents)
      except:
        times.append(str(tag.contents))
    elif 'Time' in str(tag.contents[0]):
      try:
        times[link] = crimes[link] + str(tag.contents)
      except:
        times.append(str(tag.contents))
    else:
      times.append('no automatic value')
    
    if 'Location' in str(tag.contents[0]):
      try:
        locations[link] = locations[link] + str(tag.contents)
        break
      except:
        locations.append(str(tag.contents))
        break
      break
    elif 'LOCATION' in str(tag.contents[0]):
      try:
        locations[link] = locations[link] + str(tag.contents)
        break
      except:
        locations.append(str(tag.contents))
        break
      break
    
  try:
    locations[link]
  except:
    locations.append('no automatic location')

times = times[0:200]

df = pd.DataFrame()
df['Crime'] = crimes
df['Time'] = times
df['Location'] = locations

df.to_csv('USCcrimes.csv')